/* lang-data.js — ترجمات جميع صفحات السكن
   محمّل في <head> لمنع وميض المحتوى. */

/* ══ ANTI-FLASH ══
   نخفي الصفحة فوراً في الـ head قبل أي render،
   ونطبّق اللغة المحفوظة على <html> مباشرة
   حتى لا يرى المستخدم أي وميض عند الانتقال بين الصفحات. */
(function () {
  var lang = localStorage.getItem('am_lang') || 'ar';
  var html = document.documentElement;
  html.setAttribute('lang', lang);
  html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
  html.style.opacity    = '0';
  html.style.visibility = 'hidden';
})();

window.AM_T = {

  /* ══════════════════════════════
     العربية
  ══════════════════════════════ */
  ar: {
    /* Navigation */
    nav_home:    'الرئيسية',
    nav_rooms:   'الغرف',
    nav_services:'الخدمات والمرافق',
    nav_news:    'الأخبار والفعاليات',
    nav_guide:   'دليل السكن',
    nav_contact: 'تواصل معنا',

    /* Home Hero */
    home_title: 'مرحباً بكِ في سكن الطالبات',
    home_sub1:  'بيتكِ بعيداً عن البيت — راحة، مجتمع، وموقع مميز.',
    home_sub2:  'أفضل تجربة سكن طلابي قرب الجامعة.',
    video_fallback: 'متصفحكِ لا يدعم تشغيل الفيديو.',
    music_play: 'تشغيل الموسيقى',
    music_pause: 'إيقاف الموسيقى',

    /* Home Sections */
    tag_student:    'سكن طالبات مميز',
    about_title_1:  'لأنكِ تستحقين',
    about_title_2:  'الأفضل',
    about_title_3:  'في مسيرتكِ الجامعية',
    about_desc:     'سكن الطالبات صرح سكني فاخر يضم 70 غرفة بتصميم فندقي راقٍ، مجهزة بالكامل لتوفر لكِ بيئة دراسية هادئة وحياة مريحة. كل غرفة تحتوي على مطبخ كامل، غسالة أوتوماتيك، إنترنت سريع، وخزائن حائط متكاملة — كل شيء بين يديكِ.',
    feat1_title:'أمان وحماية',        feat1_sub:'حراسة خاصة وأوقات ثابتة',
    feat2_title:'نادي صحي',           feat2_sub:'أجهزة رياضية حديثة للطالبات',
    feat3_title:'مطبخ مجهز بكل غرفة', feat3_sub:'ميكروويف، غاز، وغسالة',
    feat4_title:'إنترنت مجاني',       feat4_sub:'على مدار الساعة',
    feat5_title:'مصاعد فاخرة',        feat5_sub:'لراحة الطالبات',
    feat6_title:'مشرفات أكاديميات',   feat6_sub:'كادر ذات خبرة وكفاءة',
    location_text: 'قرب الحرم الجامعي',
    tag_vision:      'رؤيتنا',
    vision_title_1:  'بُني ليكون',
    vision_title_2:  'بيتكِ الثاني',
    vision_desc:     'صُمم السكن بعناية فائقة ليوفر لكل طالبة مساحة تشعر فيها بالأمان والانتماء. من الغرف الفاخرة إلى المرافق المشتركة الراقية، كل تفصيلة تعكس التزامنا بتقديم أعلى معايير الراحة والجودة لطالبات الجامعة.',
    feat7_title:'غرف متنوعة',     feat7_sub:'مفردة، مزدوجة، وثلاثية',
    feat8_title:'طاقة شمسية',         feat8_sub:'مياه وكهرباء مجانية',
    feat9_title:'صالة استقبال للأهالي',feat9_sub:'مجهزة بالكامل',
    feat10_title:'تواصل مباشر',       feat10_sub:'+962 7 754 44643',
    btn_facebook:  'فيسبوك',
    btn_instagram: 'إنستغرام',

    /* ── Rooms page ── */
    rooms_hero_title: 'غرفنا',
    rooms_hero_sub:   'اختاري الغرفة التي تناسب احتياجاتكِ',
    rooms_tab_single: 'مفردة',
    rooms_tab_double: 'مزدوجة',
    rooms_tab_triple: 'ثلاثية',
    rooms_royal_badge:    'ملوكي',
    rooms_ordinary_badge: 'عادية',
    rooms_vip_badge:      'VIP',
    rooms_book_btn:       'احجزي الآن',
    /* Partners */
    partners_label:        'شركاؤنا',
    partners_title_1:      'نفتخر بشراكتنا مع ',
    partners_title_2:      'أفضل الشركات',
    partners_desc:         'نتعاون مع شركات رائدة لتوفير بيئة سكنية آمنة ومتميزة لطالباتنا',
    partner_type_security: 'أمن وحماية',
    partner_type_creative: 'وكالة إبداعية',
    partner_type_tech:     'أجهزة ومعدات',
    partner_visit:         'زيارة الموقع ↗',
    room_single_royal_name:    'غرفة مفردة ملوكية',
    room_single_ordinary_name: 'غرفة مفردة عادية',
    room_double_vip_name:      'غرفة مزدوجة VIP',
    room_double_ordinary_name: 'غرفة مزدوجة عادية',
    room_triple_name:          'غرفة ثلاثية',
    rf_single_bed:    'سرير مفرد',
    rf_two_beds:      'سريران',
    rf_three_beds:    '3 أسرّة',
    rf_full_kitchen:  'مطبخ كامل',
    rf_kitchen:       'مطبخ',
    rf_shared_kitchen:'مطبخ مشترك',
    rf_private_bath:  'حمام خاص',
    rf_bath:          'حمام',
    rf_internet:      'إنترنت',
    rf_ac:            'تدفئة وتبريد',

    /* ── Services page ── */
    svc_hero_title: 'الخدمات',
    svc_hero_title_span: 'والمرافق',
    svc_hero_sub:   'كل ما تحتاجينه تحت سقف واحد',
    svc_sep1_title: 'الأمان والحراسة',
    svc_sep2_title: 'النادي الصحي',
    svc_sep3_title: 'الاستقبال والردهة',
    svc_sep4_title: 'المصاعد والممرات',
    svc_sep5_title: 'التنظيف والصيانة',
    svc_sep6_title: 'التراس والمساحات المفتوحة',
    svc_sep7_title: 'المبنى والواجهة الخارجية',
    svc_sep8_title: 'آراء الأهالي',
    svc_eyebrow_security: 'الأمان والحماية',
    svc_eyebrow_gym:      'لياقة بدنية',
    svc_eyebrow_lobby:    'ردهة وضيافة',
    svc_eyebrow_elv:      'تنقل مريح',
    svc_eyebrow_maint:    'نظافة لا تهاون فيها',
    svc_eyebrow_terrace:  'مساحة للتجدد',
    svc_eyebrow_building: 'معمار وموقع',
    svc_eyebrow_opinions: 'شهادات حقيقية',
    svc_h2_security: 'حراسة 24 ساعة بلا انقطاع',
    svc_h2_gym:      'أجهزة رياضية متكاملة حصراً للطالبات',
    svc_h2_lobby:    'ردهة فاخرة وصالة استقبال للأهالي',
    svc_h2_elv:      'مصاعد فاخرة وممرات أنيقة',
    svc_h2_maint:    'فريق تنظيف يومي وصيانة فورية',
    svc_h2_terrace:  'تراس واسع بإطلالة لا تُقاوم',
    svc_h2_building: 'واجهة معمارية راقية قرب الحرم الجامعي',
    svc_h2_opinions: 'ثقة الأسرة أكبر شهادة لنا',
    svc_p_security:  'منظومة أمنية متكاملة تضمن سلامة كل طالبة — حراسة خاصة، كاميرات CCTV، بصمة إلكترونية، ونظام إنذار حريق متطور.',
    svc_p_gym:       'نادٍ صحي واسع بأحدث الأجهزة الرياضية — لأن صحتكِ امتداد طبيعي لتفوقكِ الأكاديمي.',
    svc_p_lobby:     'ردهة استقبال فاخرة وصالة مخصصة لأهالي الطالبات — مساحة راقية للقاء والترحيب.',
    svc_p_elv:       'مصاعد حديثة وسريعة وممرات مضاءة بأناقة — راحة التنقل في كل طابق.',
    svc_p_maint:     'بيئة نظيفة تنعكس على صحتكِ وإنتاجيتكِ — تنظيف يومي بمعايير فندقية وصيانة سريعة لأي عطل.',
    svc_p_terrace:   'مساحة مفتوحة فاخرة للاسترخاء والتجمع مع الزميلات — في جو منعش بإطلالة رائعة على محيط الجامعة.',
    svc_p_building:  'مبنى فاخر بتصميم حديث في موقع استراتيجي على مسافة قصيرة من الحرم الجامعي.',
    svc_p_opinions:  'رضا الأهالي هو المقياس الحقيقي لجودتنا — آراؤهم الإيجابية جاءت تلقائية من تجربة حقيقية.',
    svc_f_sec1:'حراسة خاصة مدار الساعة',   svc_f_sec2:'كاميرات مراقبة CCTV شاملة',
    svc_f_sec3:'بصمة إلكترونية للمداخل',   svc_f_sec4:'نظام إنذار حريق متطور',
    svc_f_sec5:'أوقات دخول ثابتة ومنضبطة',
    svc_f_gym1:'أجهزة مشي Treadmill',      svc_f_gym2:'دراجات ثابتة وإهليلجية',
    svc_f_gym3:'أوزان حرة ومحطات عضلية',  svc_f_gym4:'حلبة ملاكمة',
    svc_f_gym5:'طاولة فوسبول للترفيه',
    svc_f_lob1:'ردهة رئيسية بتصميم فندقي', svc_f_lob2:'صالة مريحة لاستقبال الأهالي',
    svc_f_lob3:'ديكور أنيق وإضاءة دافئة',
    svc_f_elv1:'مصاعد حديثة وسريعة',      svc_f_elv2:'ممرات مضاءة وأنيقة',
    svc_f_elv3:'تصميم داخلي راقٍ',
    svc_f_mnt1:'تنظيف يومي بمعايير فندقية',svc_f_mnt2:'فريق صيانة متخصص',
    svc_f_mnt3:'استجابة سريعة لأي طلب',
    svc_f_ter1:'تراس واسع في أعلى المبنى',  svc_f_ter2:'إطلالة بانورامية',
    svc_f_ter3:'جلسات مريحة ومتنوعة',      svc_f_ter4:'مضاء ليلاً بشكل أنيق',
    svc_f_out1:'موقع مميز قرب الجامعة',    svc_f_out2:'تصميم معماري عصري',
    svc_f_out3:'غرف بمساحات متنوعة',   svc_f_out4:'محيط هادئ وآمن',
    svc_f_op1:'أمان تام يطمئن الأهالي',    svc_f_op2:'تواصل مستمر مع الإدارة',
    svc_f_op3:'شفافية كاملة وثقة متبادلة',

    /* ── News page ── */
        news_cat_latest:      'أحدث',
    news_cat_latest_span: 'فعالياتنا',
    news_badge_new:       'جديد',
    news_latest1_title:   'تجهيزات رمضان 2026',
    news_latest1_desc:    'أجواء رمضانية مميزة وتجهيزات خاصة استقبلت بها السكن شهر رمضان المبارك 2026.',
    news_latest2_title:   'إفطار رمضان الجماعي 2026',
    news_latest2_desc:    'مائدة إفطار جمعت طالبات السكن في أجواء رمضانية دافئة تجمع القلوب وتوحّد الأواصر.',
    news_hero_title: 'الأخبار',
    news_hero_title_span: 'والفعاليات',
    news_hero_sub:   'آخر المستجدات من السكن',
    news_filter_all:   'الكل',
    news_filter_event: 'فعاليات',
    news_filter_ann:   'إعلانات',
    news_filter_svc:   'خدمات',
    news_cat_featured: 'أبرز الفعاليات',
    news_cat_events:   'فعاليات دينية وثقافية',
    news_cat_services: 'خدمات وإعلانات',
    news_badge_event:  'فعالية',
    news_badge_ann:    'إعلان',
    news_badge_svc:    'خدمة',
    news_label_amenities: 'المرافق',
    news_label_safety:    'الأمان',
    news_ev1_title:'حفل تخرج الدفعة الجديدة 2025',
    news_ev1_desc: 'احتفالية مميزة بتخرج طالباتنا — لحظات فرح ونجاح صنعناها معاً.',
    news_ev2_title:'إفطار رمضان الجماعي 2025',
    news_ev2_desc: 'مائدة إفطار جمعت طالبات السكن في أجواء رمضانية دافئة ومميزة.',
    news_ev3_title:'الاحتفال بقدوم رمضان 2025',
    news_ev3_desc: 'فعالية ترحيبية بشهر رمضان المبارك مع الطالبات والإدارة.',
    news_ev4_title:'الاحتفال بقدوم رمضان 2024',
    news_ev4_desc: 'أجواء رمضانية جميلة جمعت ساكنات السكن في حفل مميز.',
    news_ev5_title:'الاحتفال بالمولد النبوي الشريف',
    news_ev5_desc: 'احتفاء بذكرى المولد النبوي الشريف في جو من المحبة والتواصل.',
    news_ev6_title:'إفطار رمضان الجماعي 2024',
    news_ev6_desc: 'إفطار جماعي يجمع الطالبات على مائدة رمضانية دافئة.',
    news_ev7_title:'الاحتفال بالعام الجديد',
    news_ev7_desc: 'لحظات فرح واستقبال العام الجديد مع ساكنات السكن.',
    news_ev8_title:'حفل تخرج دفعة 2024',
    news_ev8_desc: 'يوم لا يُنسى بتخرج طالباتنا المتميزات وبداية مرحلة جديدة.',
    news_sv1_title:'النادي الصحي المجهز بالكامل',
    news_sv1_desc: 'جولة داخل النادي الصحي الحصري للطالبات بكل أجهزته الحديثة.',
    news_sv2_title:'فاعلية الفيزياء التشريحية',
    news_sv2_desc: 'فعالية أكاديمية متخصصة لطالبات الكليات الطبية.',
    news_sv3_title:'جلسة تشريح جسم الإنسان',
    news_sv3_desc: 'دعم أكاديمي متخصص لطالبات كلية الطب والعلوم الصحية.',
    news_sv4_title:'فريق الصيانة الاحترافي',
    news_sv4_desc: 'استجابة فورية لأي عطل — فريق صيانة متخصص يعمل على مدار الأسبوع.',
    news_sv5_title:'آراء الأهالي — شهادات حقيقية',
    news_sv5_desc: 'الأهالي يتحدثون عن تجربتهم مع السكن وما يميزه.',
    news_sv6_title:'نظام إنذار الحريق المتطور',
    news_sv6_desc: 'منظومة أمان متكاملة تشمل كاشفات دخان وإنذار حريق في جميع الطوابق.',

    /* ── Guide page ── */
    guide_hero_title: 'دليل',
    guide_hero_span: 'السكن',
    guide_hero_sub:   'كل ما تحتاجين معرفته قبل وبعد السكن',
    guide_toc_title:     'محتويات الدليل',
    guide_toc_booking:   'خطوات الحجز',
    guide_toc_checkin:   'تسجيل الدخول',
    guide_toc_services:  'ما يشمله السكن',
    guide_toc_rules:     'القواعد والأنظمة',
    guide_toc_hours:     'المواعيد والأوقات',
    guide_toc_emergency: 'الطوارئ والتواصل',
    guide_toc_faq:       'الأسئلة الشائعة',
    guide_sec_booking:   'خطوات الحجز',
    guide_sec_checkin:   'تسجيل الدخول والاستقبال',
    guide_sec_services:  'ما يشمله السكن',
    guide_sec_rules:     'القواعد والأنظمة',
    guide_sec_hours:     'المواعيد والأوقات',
    guide_sec_emergency: 'الطوارئ والتواصل',
    guide_sec_faq:       'الأسئلة الشائعة',
    /* ── Guide page — detailed content ── */
    guide_step1: 'تواصلي معنا عبر واتساب أو الهاتف على الرقم +962 7 754 44643 أو من خلال صفحة تواصل معنا.',
    guide_step2: 'اختاري نوع الغرفة المناسبة: مفردة ملوكية، مفردة عادية، مزدوجة VIP، مزدوجة عادية، أو ثلاثية.',
    guide_step3: 'استلمي تفاصيل الأسعار والمتاح من الإدارة وتأكيد الحجز.',
    guide_step4: 'أحضري معكِ عند الوصول: صورة عن الهوية الوطنية، صورة عن البطاقة الجامعية، وإيصال الدفع.',
    guide_step5: 'استلمي مفتاح الغرفة وبطاقة الوصول البيومترية وابدئي حياتكِ الجامعية بأمان وراحة.',
    guide_checkin_h1:'موعد الدخول',      guide_checkin_p1:'يبدأ تسجيل الدخول من الساعة 7 صباحاً في يوم الانتقال المحدد مع الإدارة.',
    guide_checkin_h2:'موعد المغادرة',    guide_checkin_p2:'يجب إخلاء الغرفة قبل الساعة 12 ظهراً في يوم انتهاء الإقامة.',
    guide_checkin_h3:'وثائق مطلوبة',    guide_checkin_p3:'هوية وطنية + بطاقة جامعية + صورة شخصية حديثة.',
    guide_checkin_h4:'البصمة الإلكترونية', guide_checkin_p4:'يتم تسجيل بصمتكِ فور وصولكِ لضمان دخولكِ الآمن على مدار الساعة.',
    guide_inc_h1:'مياه وكهرباء',   guide_inc_p1:'مجانية بالكامل — لا توجد فواتير إضافية على الإطلاق.',
    guide_inc_h2:'إنترنت واي فاي', guide_inc_p2:'مجاني وعالي السرعة في جميع أرجاء المبنى 24/7.',
    guide_inc_h3:'مطبخ كامل',      guide_inc_p3:'ميكروويف، غاز، غسالة أوتوماتيك، وثلاجة في كل غرفة.',
    guide_inc_h4:'تدفئة وتبريد',   guide_inc_p4:'أنظمة تدفئة وتكييف في جميع الغرف لجميع الفصول.',
    guide_inc_h5:'نادي صحي',       guide_inc_p5:'متاح لجميع ساكنات السكن بجميع أجهزته الرياضية الحديثة.',
    guide_inc_h6:'مصاعد',          guide_inc_p6:'متاحة على مدار الساعة لجميع الطوابق.',
    guide_inc_h7:'تنظيف المشترك',  guide_inc_p7:'تنظيف يومي للممرات والمرافق المشتركة.',
    guide_inc_h8:'صيانة',          guide_inc_p8:'فريق صيانة متاح لحل أي عطل خلال فترة قصيرة.',
    guide_inc_h9:'حراسة أمنية',    guide_inc_p9:'حراسة خاصة وكاميرات مراقبة 24 ساعة / 7 أيام.',
    guide_rule1:'الالتزام بمواعيد الدخول والخروج المحددة من الإدارة.',
    guide_rule2:'المحافظة على نظافة الغرفة والمرافق المشتركة.',
    guide_rule3:'الإبلاغ الفوري عن أي عطل أو مشكلة لفريق الصيانة.',
    guide_rule4:'استقبال الأهالي في منطقة الاستقبال المخصصة فقط.',
    guide_rule5:'ممنوع منعاً باتاً إدخال أي أشخاص غير مصرح لهم إلى مناطق السكن الداخلية.',
    guide_rule6:'ممنوع إحداث أي ضجيج بعد الساعة 11 مساءً احتراماً لراحة الزميلات.',
    guide_rule7:'ممنوع إدخال أجهزة تسبب خطراً أو أضراراً على المبنى.',
    guide_rule8:'ممنوع التدخين داخل المبنى بجميع طوابقه ومرافقه.',
    guide_rule9:'أي مخالفة للأنظمة قد تستوجب الإنذار أو إنهاء العقد حسب تقدير الإدارة.',
    guide_hours_h1:'باب المبنى الرئيسي', guide_hours_p1:'يفتح: 7:00 صباحاً — يغلق: 9:00 مساءً',
    guide_hours_h2:'الدخول بعد الإغلاق', guide_hours_p2:'يتم بالبصمة الإلكترونية فقط مع إبلاغ الإدارة مسبقاً.',
    guide_hours_h3:'النادي الصحي',       guide_hours_p3:'24 ساعة / 7 أيام.',
    guide_hours_h4:'استقبال الأهالي',    guide_hours_p4:'7:00 صباحاً حتى 9:00 مساءً يومياً.',
    guide_hours_h5:'مكتب الإدارة',       guide_hours_p5:'24 ساعة / 7 أيام.',
    guide_hours_h6:'الطوارئ',            guide_hours_p6:'متاحة على مدار 24 ساعة / 7 أيام عبر الحراسة.',
    guide_emg_step0:'في حالات الطوارئ الأمنية أو الطبية تواصلي مع الحارس المناوب مباشرة في مكتب الأمن.',
    guide_emg_step1:'للإبلاغ عن عطل أو مشكلة في الغرفة اتصلي بـ فريق الصيانة عبر الإدارة.',
    guide_emg_step2:'لأي استفسار إداري أو حجز تواصلي عبر واتساب: +962 7 754 44643.',
    guide_emg_card_h4:'إدارة السكن',
    guide_emg_card_p:'نحن هنا لخدمتكِ في جميع الأوقات',
    guide_emg_card_btn:'واتساب الآن',
    guide_faq_q1:'هل المياه والكهرباء مشمولة في السعر؟',
    guide_faq_a1:'نعم، المياه والكهرباء مجانية بالكامل ومشمولة في رسوم السكن — لا توجد فواتير إضافية على الإطلاق.',
    guide_faq_q2:'هل يمكن زيارة الأهالي؟',
    guide_faq_a2:'نعم، يُسمح باستقبال الأهالي في منطقة الاستقبال المخصصة من الساعة 7 صباحاً حتى 9 مساءً يومياً.',
    guide_faq_q3:'هل النادي الصحي مجاني للطالبات؟',
    guide_faq_a3:'نعم، النادي الصحي متاح مجاناً لجميع ساكنات السكن خلال أوقات العمل الرسمية.',
    guide_faq_q4:'ما هي أنواع الغرف المتاحة؟',
    guide_faq_a4:'نوفر غرفاً متنوعة: مفردة ملوكية، مفردة عادية، مزدوجة VIP، مزدوجة عادية، وثلاثية — لمعرفة التفاصيل والأسعار يرجى التواصل معنا.',
    guide_faq_q5:'هل يمكن الدخول بعد منتصف الليل؟',
    guide_faq_a5:'يغلق الباب الرئيسي في منتصف الليل، والدخول بعد ذلك يتم بالبصمة الإلكترونية فقط مع ضرورة إبلاغ الإدارة مسبقاً.',
    guide_faq_q6:'هل يوجد إنترنت في كل أرجاء المبنى؟',
    guide_faq_a6:'نعم، يتوفر واي فاي مجاني وعالي السرعة في جميع الغرف والمرافق المشتركة على مدار الساعة.',
    guide_faq_q7:'كيف يمكن الإبلاغ عن عطل في الغرفة؟',
    guide_faq_a7:'تواصلي مع مكتب الإدارة أو عبر واتساب وسيتم إرسال فريق الصيانة في أقرب وقت ممكن.',
    guide_faq_q8:'هل السكن قريب من الجامعة؟',
    guide_faq_a8:'نعم، يقع السكن بالقرب مباشرةً من الحرم الجامعي — مسافة قصيرة مشياً.',

    /* ── Contact page ── */
    contact_hero_title: 'تواصلي',
    contact_hero_span: 'معنا',
    contact_hero_sub:   'نحن هنا للإجابة على كل أسئلتكِ',
    contact_info_title:  'معلومات التواصل',
    contact_label_wa:    'واتساب',
    contact_label_call:  'اتصال مباشر',
    contact_label_fb:    'فيسبوك',
    contact_label_ig:    'إنستغرام',
    contact_label_loc:   'الموقع',
    contact_fb_name:     'سكن الطالبات',
    contact_location:    'قرب الحرم الجامعي',
    contact_btn_wa:      'تواصلي عبر واتساب الآن',
    contact_btn_call:    'اتصلي بنا مباشرة',
    contact_btn_fb:      'راسلينا على فيسبوك',
    contact_btn_ig:      'تابعينا على إنستغرام',
    contact_form_title:  'أرسلي استفسارك عبر واتساب',
    contact_form_name:   'الاسم الكامل',
    contact_form_phone:  'رقم الهاتف',
    contact_form_uni:    'الجامعة / الكلية',
    contact_form_room:   'نوع الغرفة المطلوبة',
    contact_form_semester: 'الفصل الدراسي المطلوب',
    contact_form_msg:    'رسالتكِ أو أي تفاصيل إضافية',
    contact_form_submit: 'إرسال عبر واتساب',
    contact_form_note:   'سيتم فتح واتساب برسالتكِ تلقائياً — سريع وبدون تعقيد',
    contact_sending:     'جاري فتح واتساب...',
    contact_room_placeholder: '— اختاري نوع الغرفة —',
    contact_room_general: 'استفسار عام',
    contact_sem_placeholder: '— اختاري —',
    contact_ph_name:  'اسمكِ الكريم',
    contact_ph_uni:   'مثال: اسم الجامعة — الكلية',
    contact_ph_msg:   'اكتبي استفساركِ أو أي ملاحظات...',
    contact_sem1:     'الفصل الأول 2025/2026',
    contact_sem2:     'الفصل الثاني 2025/2026',
    contact_sem3:     'الفصل الصيفي 2026',
    contact_map_title:'موقعنا على الخريطة',
    contact_map_strip:'قرب الحرم الجامعي — اضغطي لعرض الموقع',
    contact_alert_name:'من فضلكِ أدخلي اسمكِ',

    /* Footer */
    footer_text: '© 2026 نموذج سكن طلابي - جميع الحقوق محفوظة',
    footer_credit:"تصميم وتطوير: Loʘk",
  },

  /* ══════════════════════════════
     English
  ══════════════════════════════ */
  en: {
    /* Navigation */
    nav_home:    'Home',
    nav_rooms:   'Rooms',
    nav_services:'Services & Amenities',
    nav_news:    'News & Events',
    nav_guide:   'Resident Guide',
    nav_contact: 'Contact Us',

    /* Home Hero */
    home_title: 'Welcome to Student Housing for Female Students',
    home_sub1:  'Your home away from home — comfort, community & convenience.',
    home_sub2:  "The best student accommodation near the University.",
    video_fallback: 'Your browser does not support video playback.',
    music_play: 'Play music',
    music_pause: 'Pause music',

    /* Home Sections */
    tag_student:    "Exclusive Women's Dorm",
    about_title_1:  'Because You Deserve',
    about_title_2:  'the Best',
    about_title_3:  'in Your Academic Journey',
    about_desc:     "Student Housing is a premium premium hotel-style residence featuring 70 fully furnished rooms designed to provide a quiet study environment and comfortable living. Every room includes a full kitchen, automatic washer, high-speed internet, and built-in wardrobes.",
    feat1_title:'Safety & Security',         feat1_sub:'Private security & fixed hours',
    feat2_title:'Fitness Center',            feat2_sub:'Modern gym for female students',
    feat3_title:'Full Kitchen in Every Room',feat3_sub:'Microwave, stove & washer',
    feat4_title:'Free Internet',             feat4_sub:'Available 24/7',
    feat5_title:'Luxury Elevators',          feat5_sub:"For residents' convenience",
    feat6_title:'Academic Supervisors',      feat6_sub:'Experienced & professional staff',
    location_text: "Near the University Campus",
    tag_vision:     'Our Vision',
    vision_title_1: 'Built to Be',
    vision_title_2: 'Your Second Home',
    vision_desc:    "Student Housing was carefully designed to give every student a space where she feels safe and at home. From luxurious rooms to premium shared facilities — every detail reflects our commitment to the highest standards of comfort and quality.",
    feat7_title:'Varied Rooms',        feat7_sub:'Single, double & triple',
    feat8_title:'Solar Energy',           feat8_sub:'Free water & electricity',
    feat9_title:'Family Reception Lounge',feat9_sub:'Fully equipped',
    feat10_title:'Direct Contact',        feat10_sub:'+962 7 754 44643',
    btn_facebook:  'Facebook',
    btn_instagram: 'Instagram',

    /* ── Rooms page ── */
    rooms_hero_title: 'Our Rooms',
    rooms_hero_sub:   'Choose the room that suits you best',
    rooms_tab_single: 'Single',
    rooms_tab_double: 'Double',
    rooms_tab_triple: 'Triple',
    rooms_royal_badge:    'Royal',
    rooms_ordinary_badge: 'Standard',
    rooms_vip_badge:      'VIP',
    rooms_book_btn:       'Book Now',
    /* Partners */
    partners_label:        'Our Partners',
    partners_title_1:      'Proud to Partner with ',
    partners_title_2:      'the Best',
    partners_desc:         'We collaborate with leading companies to provide a safe and premium living environment',
    partner_type_security: 'Security & Protection',
    partner_type_creative: 'Creative Agency',
    partner_type_tech:     'Appliances & Equipment',
    partner_visit:         'Visit Website ↗',
    room_single_royal_name:    'Royal Single Room',
    room_single_ordinary_name: 'Standard Single Room',
    room_double_vip_name:      'VIP Double Room',
    room_double_ordinary_name: 'Standard Double Room',
    room_triple_name:          'Triple Room',
    rf_single_bed:    'Single bed',
    rf_two_beds:      'Two beds',
    rf_three_beds:    '3 beds',
    rf_full_kitchen:  'Full kitchen',
    rf_kitchen:       'Kitchen',
    rf_shared_kitchen:'Shared kitchen',
    rf_private_bath:  'Private bathroom',
    rf_bath:          'Bathroom',
    rf_internet:      'Internet',
    rf_ac:            'Heating & cooling',

    /* ── Services page ── */
    svc_hero_title: 'Services &',
    svc_hero_title_span: 'Amenities',
    svc_hero_sub:   'Everything you need under one roof',
    svc_sep1_title: 'Security & Guard',
    svc_sep2_title: 'Fitness Center',
    svc_sep3_title: 'Lobby & Reception',
    svc_sep4_title: 'Elevators & Hallways',
    svc_sep5_title: 'Cleaning & Maintenance',
    svc_sep6_title: 'Terrace & Open Spaces',
    svc_sep7_title: 'Building & Exterior',
    svc_sep8_title: "Parents' Reviews",
    svc_eyebrow_security: 'Safety & Protection',
    svc_eyebrow_gym:      'Fitness',
    svc_eyebrow_lobby:    'Lobby & Hospitality',
    svc_eyebrow_elv:      'Comfortable Mobility',
    svc_eyebrow_maint:    'Zero-Compromise Cleanliness',
    svc_eyebrow_terrace:  'Space to Recharge',
    svc_eyebrow_building: 'Architecture & Location',
    svc_eyebrow_opinions: 'Real Testimonials',
    svc_h2_security: '24-Hour Guard — Non-Stop',
    svc_h2_gym:      'Full Gym Equipment — Exclusively for Residents',
    svc_h2_lobby:    'Luxury Lobby & Family Reception Lounge',
    svc_h2_elv:      'Luxury Elevators & Elegant Hallways',
    svc_h2_maint:    'Daily Cleaning Team & Instant Maintenance',
    svc_h2_terrace:  'Spacious Terrace with Breathtaking Views',
    svc_h2_building: "Premium Architecture Near Campus",
    svc_h2_opinions: "Family Trust Is Our Greatest Testimonial",
    svc_p_security:  'A comprehensive security system to keep every resident safe — private guards, CCTV cameras, fingerprint access, and an advanced fire alarm.',
    svc_p_gym:       'A spacious gym with the latest equipment — because your health is a natural extension of your academic success.',
    svc_p_lobby:     'A luxurious main lobby and a dedicated family lounge — an elegant space for meetings and warm welcomes.',
    svc_p_elv:       'Modern, fast elevators and elegantly lit hallways — comfortable movement on every floor.',
    svc_p_maint:     'A clean environment reflects your health and productivity — daily hotel-standard cleaning and fast maintenance for any issue.',
    svc_p_terrace:   'A premium open space for relaxation and socialising with fellow residents — a refreshing atmosphere overlooking the university.',
    svc_p_building:  "A luxury building with modern design in a prime location — a short walk from the University campus.",
    svc_p_opinions:  "Parents' satisfaction is the true measure of our quality — their positive feedback comes naturally from a genuine experience.",
    svc_f_sec1:'Round-the-clock private security',  svc_f_sec2:'Comprehensive CCTV surveillance',
    svc_f_sec3:'Fingerprint access control',        svc_f_sec4:'Advanced fire alarm system',
    svc_f_sec5:'Fixed & regulated entry hours',
    svc_f_gym1:'Treadmill machines',                svc_f_gym2:'Stationary & elliptical bikes',
    svc_f_gym3:'Free weights & weight stations',    svc_f_gym4:'Boxing ring',
    svc_f_gym5:'Foosball table for recreation',
    svc_f_lob1:'Main lobby with hotel-style design', svc_f_lob2:'Comfortable family reception lounge',
    svc_f_lob3:'Elegant décor & warm lighting',
    svc_f_elv1:'Modern fast elevators',             svc_f_elv2:'Elegantly lit hallways',
    svc_f_elv3:'Premium interior design',
    svc_f_mnt1:'Daily hotel-standard cleaning',     svc_f_mnt2:'Dedicated maintenance team',
    svc_f_mnt3:'Fast response to any request',
    svc_f_ter1:'Rooftop terrace',                   svc_f_ter2:'Panoramic views',
    svc_f_ter3:'Varied comfortable seating',        svc_f_ter4:'Elegantly lit at night',
    svc_f_out1:'Prime location near the university', svc_f_out2:'Modern architectural design',
    svc_f_out3:'Rooms with varied layouts',      svc_f_out4:'Quiet & safe surroundings',
    svc_f_op1:'Full security reassures families',   svc_f_op2:'Continuous contact with management',
    svc_f_op3:'Full transparency & mutual trust',

    /* ── News page ── */
        news_cat_latest:      'Latest',
    news_cat_latest_span: 'Events',
    news_badge_new:       'New',
    news_latest1_title:   'Ramadan 2026 Decorations',
    news_latest1_desc:    'A special Ramadan atmosphere as Student Housing welcomed the holy month of Ramadan 2026.',
    news_latest2_title:   'Ramadan Iftar 2026',
    news_latest2_desc:    'A communal iftar table that brought together the residents in a warm and memorable Ramadan evening.',
    news_hero_title: 'News &',
    news_hero_title_span: 'Events',
    news_hero_sub:   'Latest updates from Student Housing',
    news_filter_all:   'All',
    news_filter_event: 'Events',
    news_filter_ann:   'Announcements',
    news_filter_svc:   'Services',
    news_cat_featured: 'Featured Events',
    news_cat_events:   'Religious & Cultural Events',
    news_cat_services: 'Services & Announcements',
    news_badge_event:  'Event',
    news_badge_ann:    'Announcement',
    news_badge_svc:    'Service',
    news_label_amenities: 'Amenities',
    news_label_safety:    'Safety',
    news_ev1_title:'Graduation Ceremony 2025',
    news_ev1_desc: 'A special celebration for our graduating students — moments of joy and success we created together.',
    news_ev2_title:'Ramadan Group Iftar 2025',
    news_ev2_desc: 'An Iftar table that brought resident students together in a warm and memorable Ramadan atmosphere.',
    news_ev3_title:'Welcoming Ramadan 2025',
    news_ev3_desc: 'A welcome celebration for the holy month of Ramadan with students and management.',
    news_ev4_title:'Welcoming Ramadan 2024',
    news_ev4_desc: 'Beautiful Ramadan atmosphere bringing residents together in a special celebration.',
    news_ev5_title:"Prophet's Birthday Celebration",
    news_ev5_desc: "A celebration marking the Prophet's Birthday in an atmosphere of love and togetherness.",
    news_ev6_title:'Ramadan Group Iftar 2024',
    news_ev6_desc: 'A group Iftar bringing students together at a warm Ramadan table.',
    news_ev7_title:'New Year Celebration',
    news_ev7_desc: 'Joyful moments welcoming the new year with our residents.',
    news_ev8_title:'Graduation Ceremony 2024',
    news_ev8_desc: 'An unforgettable day as our outstanding students graduate and begin a new chapter.',
    news_sv1_title:'Fully Equipped Fitness Center',
    news_sv1_desc: 'A tour inside the exclusive gym for residents featuring all modern equipment.',
    news_sv2_title:'Anatomical Physics Workshop',
    news_sv2_desc: 'A specialised academic workshop for medical faculty students.',
    news_sv3_title:'Human Anatomy Session',
    news_sv3_desc: 'Specialised academic support for medical and health sciences students.',
    news_sv4_title:'Professional Maintenance Team',
    news_sv4_desc: 'Instant response to any issue — a dedicated maintenance team working around the week.',
    news_sv5_title:"Parents' Reviews — Real Testimonials",
    news_sv5_desc: 'Parents share their experience with Student Housing and what sets it apart.',
    news_sv6_title:'Advanced Fire Alarm System',
    news_sv6_desc: 'A comprehensive safety system including smoke detectors and fire alarms on all floors.',

    /* ── Guide page ── */
    guide_hero_span: 'Guide',
    guide_hero_title: 'Resident',
    guide_hero_sub:   'Everything you need to know before and after moving in',
    guide_toc_title:     'Guide Contents',
    guide_toc_booking:   'Booking Steps',
    guide_toc_checkin:   'Check-In',
    guide_toc_services:  'What Is Included',
    guide_toc_rules:     'Rules & Regulations',
    guide_toc_hours:     'Schedules & Hours',
    guide_toc_emergency: 'Emergency & Contact',
    guide_toc_faq:       'FAQ',
    guide_sec_booking:   'Booking Steps',
    guide_sec_checkin:   'Check-In & Reception',
    guide_sec_services:  'What Is Included',
    guide_sec_rules:     'Rules & Regulations',
    guide_sec_hours:     'Schedules & Hours',
    guide_sec_emergency: 'Emergency & Contact',
    guide_sec_faq:       'Frequently Asked Questions',
    /* ── Guide page — detailed content ── */
    guide_step1: "Contact us via WhatsApp or phone at +962 7 754 44643 or through the Contact Us page.",
    guide_step2: "Choose the suitable room type: Royal Single, Standard Single, VIP Double, Standard Double, or Triple.",
    guide_step3: "Receive pricing and availability details from management and booking confirmation.",
    guide_step4: "Bring upon arrival: a copy of your national ID, university card, and payment receipt.",
    guide_step5: "Receive your room key and biometric access card, and begin your university life safely and comfortably.",
    guide_checkin_h1:'Check-In Time',       guide_checkin_p1:'Check-in starts from 7:00 AM on the move-in day agreed with management.',
    guide_checkin_h2:'Check-Out Time',      guide_checkin_p2:'The room must be vacated before 12:00 PM on the last day of stay.',
    guide_checkin_h3:'Required Documents',  guide_checkin_p3:'National ID + University card + recent personal photo.',
    guide_checkin_h4:'Fingerprint Access',  guide_checkin_p4:'Your fingerprint is registered upon arrival for secure access around the clock.',
    guide_inc_h1:'Water & Electricity', guide_inc_p1:'Completely free — no additional bills whatsoever.',
    guide_inc_h2:'Wi-Fi Internet',      guide_inc_p2:'Free high-speed internet throughout the building 24/7.',
    guide_inc_h3:'Full Kitchen',        guide_inc_p3:'Microwave, stove, automatic washer, and fridge in every room.',
    guide_inc_h4:'Heating & Cooling',   guide_inc_p4:'Heating and AC systems in all rooms for all seasons.',
    guide_inc_h5:'Fitness Center',      guide_inc_p5:'Available to all residents with all modern gym equipment.',
    guide_inc_h6:'Elevators',           guide_inc_p6:'Available around the clock for all floors.',
    guide_inc_h7:'Common Area Cleaning',guide_inc_p7:'Daily cleaning of hallways and shared facilities.',
    guide_inc_h8:'Maintenance',         guide_inc_p8:'A maintenance team available to resolve any issue quickly.',
    guide_inc_h9:'Security Guard',      guide_inc_p9:'Private security and CCTV cameras 24 hours / 7 days.',
    guide_rule1:'Commit to entry and exit times set by management.',
    guide_rule2:'Keep the room and shared facilities clean.',
    guide_rule3:'Report any malfunction or issue to the maintenance team immediately.',
    guide_rule4:'Receive family visitors in the designated reception area only.',
    guide_rule5:'Strictly prohibited: bringing unauthorized persons into the residential areas.',
    guide_rule6:'Prohibited: causing noise after 11:00 PM out of respect for fellow residents.',
    guide_rule7:'Prohibited: bringing devices that pose a risk or damage to the building.',
    guide_rule8:'Prohibited: smoking inside the building on all floors and in all facilities.',
    guide_rule9:'Any violation may result in a warning or contract termination at management discretion.',
    guide_hours_h1:'Main Building Door', guide_hours_p1:'Opens: 7:00 AM — Closes: 9:00 PM',
    guide_hours_h2:'After-Hours Entry',  guide_hours_p2:'Via fingerprint only with prior notice to management.',
    guide_hours_h3:'Fitness Center',     guide_hours_p3:'24 hours / 7 days.',
    guide_hours_h4:'Family Reception',   guide_hours_p4:'7:00 AM to 9:00 PM daily.',
    guide_hours_h5:'Management Office',  guide_hours_p5:'24 hours / 7 days.',
    guide_hours_h6:'Emergencies',        guide_hours_p6:'Available 24 hours / 7 days through the security guard.',
    guide_emg_step0:'In security or medical emergencies, contact the on-duty guard directly at the security office.',
    guide_emg_step1:'To report a room malfunction, call the maintenance team through management.',
    guide_emg_step2:'For any administrative inquiry or booking, contact us via WhatsApp: +962 7 754 44643.',
    guide_emg_card_h4:'Residence Management',
    guide_emg_card_p:'We are here to serve you at all times',
    guide_emg_card_btn:'WhatsApp Now',
    guide_faq_q1:'Are water and electricity included in the price?',
    guide_faq_a1:'Yes, water and electricity are completely free and included in accommodation fees — no additional bills at all.',
    guide_faq_q2:'Can family members visit?',
    guide_faq_a2:'Yes, family visits are allowed in the designated reception area from 7:00 AM to 9:00 PM daily.',
    guide_faq_q3:'Is the fitness center free for residents?',
    guide_faq_a3:'Yes, the fitness center is freely available to all Student Housing residents during official hours.',
    guide_faq_q4:'What room types are available?',
    guide_faq_a4:'We offer: Royal Single, Standard Single, VIP Double, Standard Double, and Triple — contact us for pricing.',
    guide_faq_q5:'Can I enter after midnight?',
    guide_faq_a5:'The main door closes at midnight; entry after requires fingerprint access and prior notification to management.',
    guide_faq_q6:'Is there internet throughout the building?',
    guide_faq_a6:'Yes, free high-speed Wi-Fi is available in all rooms and shared facilities around the clock.',
    guide_faq_q7:'How do I report a room malfunction?',
    guide_faq_a7:'Contact the management office or via WhatsApp and the maintenance team will be sent as soon as possible.',
    guide_faq_q8:"Is the dorm close to the University?",
    guide_faq_a8:"Yes, Student Housing is located close to the University campus — a short walk.",

    /* ── Contact page ── */
    contact_hero_title: 'Contact',
    contact_hero_span: 'Us',
    contact_hero_sub:   "We're here to answer all your questions",
    contact_info_title:  'Contact Information',
    contact_label_wa:    'WhatsApp',
    contact_label_call:  'Direct Call',
    contact_label_fb:    'Facebook',
    contact_label_ig:    'Instagram',
    contact_label_loc:   'Location',
    contact_fb_name:     'Student Housing',
    contact_location:    "Near the University Campus",
    contact_btn_wa:      'Chat on WhatsApp Now',
    contact_btn_call:    'Call Us Directly',
    contact_btn_fb:      'Message Us on Facebook',
    contact_btn_ig:      'Follow Us on Instagram',
    contact_form_title:  'Send Your Inquiry via WhatsApp',
    contact_form_name:   'Full Name',
    contact_form_phone:  'Phone Number',
    contact_form_uni:    'University / Faculty',
    contact_form_room:   'Room Type Requested',
    contact_form_semester: 'Semester Requested',
    contact_form_msg:    'Your message or any additional details',
    contact_form_submit: 'Send via WhatsApp',
    contact_form_note:   'WhatsApp will open automatically with your message — quick and easy',
    contact_sending:     'Opening WhatsApp...',
    contact_room_placeholder: '— Choose room type —',
    contact_room_general: 'General inquiry',
    contact_sem_placeholder: '— Choose —',
    contact_ph_name:  'Your full name',
    contact_ph_uni:   "Example: University Name — Faculty of Science",
    contact_ph_msg:   'Write your inquiry or any notes...',
    contact_sem1:     'First Semester 2025/2026',
    contact_sem2:     'Second Semester 2025/2026',
    contact_sem3:     'Summer Semester 2026',
    contact_map_title:'Our Location on the Map',
    contact_map_strip:"Near the University Campus — Tap to open the map",
    contact_alert_name:'Please enter your name',

    /* Footer */
    footer_text: "© 2026 Student Housing Prototype - All rights reserved",
    footer_credit:"Design & Development: Loʘk",
  }
};

/* أضف transition على html حتى يظهر بسلاسة عند كشف الصفحة */
(function () {
  var style = document.createElement('style');
  style.textContent = 'html { transition: opacity 0.15s ease; }';
  document.head.appendChild(style);
})();
